export const API_ENDPOINTS = {
  ai: {
    hostScriptSuggestions: '/v1/ai/host-script-suggestions',
    speechRefineText: '/v1/ai/speech-refine-text',
  },
  client: {
    errorReport: '/v1/client-error',
  },
  files: {
    list: '/v1/files',
    upload: '/v1/upload',
  },
  mobile: {
    links: '/v1/mobile/links',
  },
  music: {
    backendControl: '/v1/music/backend-control',
    backendPlay: '/v1/music/backend-play',
    backendState: '/v1/music/backend-state',
    backendVolume: '/v1/music/backend-volume',
    musicList: '/v1/music/musiclist',
    musicListExportPdf: '/v1/music/musiclist/export-pdf',
    musicListRuntimeTrack: '/v1/music/musiclist/runtime-track',
    musicListSave: '/v1/music/musiclist/save',
    previewSource: '/v1/music/preview-source',
    showCurrent: '/v1/music/show/current',
    showCurrentClose: '/v1/music/show/current/close',
    showCurrentLock: '/v1/music/show/current-lock',
    showCurrentProgram: '/v1/music/show/current-program',
    showCurrentState: '/v1/music/show/current-state',
    showDetail: (fileName) => `/v1/music/show/${encodeURIComponent(fileName)}`,
    shows: '/v1/music/shows',
  },
  recording: {
    detail: (fileName) => `/v1/recording/${encodeURIComponent(fileName)}`,
    listInputDevices: '/v1/recording/list-input-devices',
    listOutputDevices: '/v1/recording/list-output-devices',
    listRecordings: '/v1/recording/list-recordings',
    recordingStatus: '/v1/recording/recording-status',
    startBackend: '/v1/recording/start-recording-backend',
    startLiveMicPlayback: '/v1/recording/start-live-mic-playback',
    stopBackend: '/v1/recording/stop-recording-backend',
    stopLiveMicPlayback: '/v1/recording/stop-live-mic-playback',
    switchOutputDevice: '/v1/recording/switch-output-device',
    useRecording: '/v1/recording/use-recording',
  },
  settings: {
    user: '/v1/settings',
  },
  stream: {
    backendProgress: '/v1/music/backend-progress/stream',
  },
  webrtc: {
    consumerResume: (consumerId) => `/v1/webrtc/consumers/${consumerId}/resume`,
    rtpCapabilities: '/v1/webrtc/rtp-capabilities',
    sessionDetail: (sessionId) => `/v1/webrtc/sessions/${sessionId}`,
    sessionProducers: (sessionId) => `/v1/webrtc/sessions/${sessionId}/producers`,
    sessions: '/v1/webrtc/sessions',
    transportConnect: (transportId) => `/v1/webrtc/transports/${transportId}/connect`,
    transportConsume: (transportId) => `/v1/webrtc/transports/${transportId}/consume`,
    transportDetail: (transportId) => `/v1/webrtc/transports/${transportId}`,
    transportProduce: (transportId) => `/v1/webrtc/transports/${transportId}/produce`,
    transports: '/v1/webrtc/transports',
  },
}